### ISSUE TITLE
x86 MacOS download not working on arm64 - build machine needs QEMU, binfmt and ldid setup

### ISSUE THREAD

**Issue by cliffordfajardo** [c9fe/22120#101]
MacOS download not working. Should the MacOS file in the [releases page](https://github.com/i5ik/Diskernet/releases) be a `.dmg` file?
I downloaded the file and when I opened it, it was opened in my textedit application

<img width="672" alt="CleanShot 2022-01-04 at 10 59 17@2x" src="https://user-images.githubusercontent.com/6743796/148109895-d08fcae0-8ae9-4c1e-b762-2712c56cecd7.png">

**Comment by crisdosaygo** [comment]
Wow, thank you! I think Mac may be tricky because maybe I need to sign up for an apple dev account and do code signing? But I'm not a Mac expert...maybe someone knows how pkg (that I use for bundling) affects this and how it's normally handled?

In the meantime you could try the npm global install

**Comment by crisdosaygo** [comment]
I changed the title to reflect what I think this issue is...I'm pretty sure because I built on an x86 machine, that your mac must use the arm architecture...so these binaries will not work on there. 

You'll need to build your own arm architecture build to use a binary on your mac i think.

**Comment by crisdosaygo** [comment]
Heh I actually think it is possible for me to build arm on linux, i just have to set up QEMU:

https://wiki.debian.org/QemuUserEmulation
