### ISSUE TITLE
its not running on ubuntu

### ISSUE THREAD

**Issue by 10sp** [c9fe/22120#121]
![Screenshot from 2022-03-23 01-52-32](https://user-images.githubusercontent.com/12599480/159569317-aea88122-b6a7-4230-84e2-db73ad548c9f.png)

**Comment by crisdosaygo** [comment]
Thanks for report

You need to start the app first, then it will open a server on 22120. If you still have issues, output from the console might be helpful.

If you still have issues, I don't know what the problem is sorry!
