### ISSUE TITLE
Consider relicensing?

### ISSUE THREAD

**Issue by OliverEvans96** [c9fe/22120#122]
Hello,

I'm interested in this project, but the license doesn't seem to grant me permission to modify the source code. If you allow others to hack on the project with you, it might generate more interest & engagement.

Just a thought. If I'm mistaken, please correct me. Anyways, thanks for sharing.

Oliver

**Comment by crisdosaygo** [comment]
Hey Oliver

You're right about the current license.

I'm trying to balance giving it for free with protecting it from being ripped off for commercial purposes.

I had more permissive licenses in the past but I found even with thousands of stars, people don't actually submit significant PRs (beyond README typos), they mostly just raise issues or ask me to fix stuff.

So the freedom to modify wasn't much needed even when it was available. Sure, that does not cover everyone. You'd like to modify it, and surely there are other people who don't want to rip it off commercially but only want to improve it. I'm sure they exist!

So based on your comment let me reconsider what licensing I might release DK under. I'm happy with the current one but I want to make sure it's optimal.

Thank you for your contribution! 

🙂

**Comment by OliverEvans96** [comment]
Thanks for the consideration, and I totally respect your experience and
whichever decision you make!
