### ISSUE TITLE
monthly perpetual license?

### ISSUE THREAD

**Issue by matkoniecz** [c9fe/22120#127]
![screen29](https://user-images.githubusercontent.com/899988/187392887-a4188fa5-1310-4b51-96fb-25ba97ed5eed.png)

how it actually works? What happens when I stop paying monthly for this perpetual license?

**Comment by crisdosaygo** [comment]
Hi @matkoniecz thank you. I'm rethinking licensing and fees. I don't have an update right now, but when I do, I'll post one.

Thanks! :) ;p xx ;p
