### ISSUE TITLE
Feature request: Scoop or Windows Package Manager release channels

### ISSUE THREAD

**Issue by worldofgeese** [c9fe/22120#131]
The Windows Package Manager now supports portable/standalone binaries as of 1.3 and `scoop` is a very popular package manager on Windows used for installing everything from `kubectl` to the AWS CLI. I would so enjoy release channels supporting either of these package managers.

**Comment by crisdosaygo** [comment]
Yes, I was already considering widening and extending my distribution, including package managers or stores, before your feature request. I don't think I had thought of or knew about scoop, or much about Windows Package Manager. Thank you!

**Comment by crisdosaygo** [comment]
Related

Verifying install scripts

https://checksum.sh/

**Comment by crisdosaygo** [comment]
@worldofgeese would you like to try doing PR on this?
