### ISSUE TITLE
Add instructions for cloning and running

### ISSUE THREAD

**Issue by crisdosaygo** [c9fe/22120#166]

**Comment by TangentFoxy** [comment]
Do you have any idea how to do either of these things? I can't figure it out.

**Comment by crisdosaygo** [comment]
Heh, that should be in the README already, @TangentFoxy - I see that it isn't tho! Thanks for the reminder to put that in. 

When I've got a bit of time I will take a look, sorry I can't be of more help immediately. I suggest you try to clone the repo, and run 'npm test' or 'npm start' from in the repo directory to see if that does something. Does that help at all? Let us know how it goes, and thank you again for the reminder!

**Comment by TangentFoxy** [comment]
> run 'npm test' or 'npm start' from in the repo directory

Following the readme for installing this tells me to use the `-g` flag, so I have no idea where "the repo directory" is? Unless I'm supposed to also clone this repo? The readme doesn't say to clone it in addition to installing it that way.

(If it helps in providing feedback, I have never used NPM before, so if there's some kind of "should be obvious to a dev using NPM" thing, I have no idea what I'd be missing there.)

**Comment by crisdosaygo** [comment]
@TangentFoxy I can't help you with how to use NPM we don't make that so it's not our responsibility of course - but how about you do what I do when you encounter something you don't yet know: just ask ChatGPT! 🤣
