### ISSUE TITLE
First run hangs on Windows 7

### ISSUE THREAD

**Issue by JL01152** [c9fe/22120#177]
![20231210012442_screenshot](https://github.com/dosyago/DownloadNet/assets/1390301/0a53862a-0456-4ba7-a5ac-857f7b831770)

I've been looking for a Memex replacement for ages it seems. I found this and it looks promising. I abosolutely need it but I cant even get it to install. Any help?

**Comment by crisdosaygo** [comment]
Sure, happy to help @JL01152 

Would you mind saying what you're looking for in a Memex replacement? I thought Memex was pretty good.

Anyway, for your stuck installation it's possible we need to update the release to fix it, or it could be another issue. To help look into it, would you mind setting the environment variable DEBUG_22120, then running again?

**Comment by crisdosaygo** [comment]
Closing as no updates.

**Comment by JL01152** [comment]
Sorry, For some reason I am not getting notified of these messages. I had not checked back in . I am now seeing this 2 weeks later. My apologies. 

As for what I'm looking for in memex is being able to cross-reference what I had previously read in web pages. My adhd/ ocd get the best of me and I spend hours trying to backtrack finding where I had previously read something similar. Memex used to be able to do this now I have no such luck. 

Anyway, How do I do this?

"To help look into it, would you mind setting the environment variable DEBUG_22120, then running again?"

**Comment by crisdosaygo** [comment]
Thanks for saying that. No worries about the late reply tho, I understand what you mean. I love the internet's async nature. Hopefully gives us all more free time or freedom!

> My adhd/ ocd get the best of me and I spend hours trying to backtrack finding where I had previously read something similar. Memex used to be able to do this now I have no such luck.

Well DownloadNet will definitely help you here. The full text search of what you've read will let you be able to jump back to it, up to the limit of how well the search works. Which seems ok. 

It's not the best search engine in the world, but it definitely helps that use case. The fact that it's already pre-filtered by stuff you've looked at is a significant signal and improvement on general search often!

I've copied some instructions for you from ChatGPT, hopefully that works! :)


------

To set an environment variable in Windows from the command line and then run a command, you can use the following steps:

1. **Open Command Prompt**: You can do this by searching for 'cmd' in the Start menu or by pressing `Win + R`, typing `cmd`, and hitting Enter.

2. **Set the Environment Variable**: Use the `set` command to define your environment variable. For example:
   ```
   set MYVAR=value
   ```

3. **Run Your Command**: After setting the environment variable, you can run any command in the same Command Prompt window. The environment variable you set will be available to this command.

Remember, this method sets the environment variable temporarily for the current session of the Command Prompt. The variable will not be available in other Command Prompt windows or after you close this window. To set a permanent environment variable, you would use the System Properties or the `setx` command.

-----

After you set that var, then please run the command executable again from the same shell window. 👍🏻 :)

**Comment by JL01152** [comment]
![image](https://github.com/dosyago/DownloadNet/assets/1390301/d613ab3d-e152-4bd9-8c9e-d97fa4a03ce1)

This is what I get.

**Comment by crisdosaygo** [comment]
Oh, `DEBUG_22120` is the variable name, set to any non empty value. 

Just do some research on setting an environment variable in windows and if you get confident doing that, come back and we can try any next steps! :) Thank you

**Comment by JL01152** [comment]
I was not familiar to setting environment variables that way. I had set paths as environment variables to be able to access a program on the command line anywhere. I was not aware of this method. 

I tried set DEBUG_22120=0 and that did nothing either. I'll look up on google and see what I'm doing wrong with that. I'll report back

**Comment by JL01152** [comment]
DEBUG_22120*

**Comment by JL01152** [comment]
![image](https://github.com/dosyago/DownloadNet/assets/1390301/0bd98b25-1378-46dc-9c8a-61ae7cc2ee7a)
