### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by mhucka** [c9fe/22120#182]
The description for this repository is currently this:

<img width="373" alt="image" src="https://github.com/dosyago/DownloadNet/assets/1450019/a1fd832c-d236-4255-9d0b-14438ff58780">

The "All content your browse ..." should be "All content you browse", i.e., "your" -→ "you".

**Comment by crisdosaygo** [comment]
Hello, sir @mhucka thank you very much for that! We will get right on it and correct it right away! :)
