### ISSUE TITLE
Confused about name of this project

### ISSUE THREAD

**Issue by mhucka** [c9fe/22120#183]
The name of the repository, and the name in the repo description, is "DownloadNet". However, the README uses the name "DiskerNet". What is the correct name?

<img width="1041" alt="image" src="https://github.com/dosyago/DownloadNet/assets/1450019/f738f1e3-d31b-4a48-adb4-1d9ce49f9fd1">

**Comment by crisdosaygo** [comment]
Hello sir @mhucka thank you for bringing this to our attention! We will get right on it and correct it immediately. 

The name *used to be* DiskerNet, but I changed it to DownloadNet. Do you have a preference? 

DiskerNet, I suppose, is more unique. And I like the image of the floppy disk - 'early' computers of my youth you see! Haha :)

DownloadNet is more 'accurate' I guess. Alternately, there's probably a better name. What ideas do you have, sir? :)

*For now I've updated to DownloadNet, but I want to consider any ideas you have in future! :)*
