### ISSUE TITLE
Latest release in april has no binaries

### ISSUE THREAD

**Issue by paulito1** [c9fe/22120#190]
v3.0.1 - freshen
only shows 2 source file downloads

The prior release has binaries in 3 formats. 
It is easier for people if up to date binaries are available.

**Comment by crisdosaygo** [comment]
Hi @paulito1 thanks for that idea! Yes, releases have normally signalled binaries available in this project. 

It was just a bit difficult to create the binaries, build has some issues, and I couldn't be bothered. But when I get around to it I will put some binaries out.

Hope you can wait until then! :)

Are you having any issues with the previous version? :)

**Comment by crisdosaygo** [comment]
New mac binary is on latest thanks @paulito1 !
