### ISSUE TITLE
FR: Run in background/don't autolaunch chrome

### ISSUE THREAD

**Issue by brimwats** [c9fe/22120#192]
Hello!

I largely use Vivaldi; I was hoping to try DiskerNet/DownloadNet out to see if it would be useful for archivists, but currently on windows it launches a cmd window and also a chrome window, neither of which I particularly need in the background. Any thoughts?

**Comment by crisdosaygo** [comment]
Yes, it's a good idea to support other browsers. The code changes are not so much, we just have not made it a priority right now. You're welcome to go for a PR if you want, or you can wait until we eventually get to this. Regarding the cmd window, it might be possible to hide that on Windows, but perhaps not, I'm unsure. 

Seem to remember windows having some requirements for displaying CMD window when running shell commands. You're probably right we could put it in background, might take a bit of finessing to get it there. 

If you're interested in approaching this work, please let me know and I can guide you and point you at some samples that might help, but I totally understand if you'd rather not!

Definitely we will get to improvements like this in time, I feel sorry for you (and many others!) that it hasn't met your expectation so far, it's just not a priority for us right now. That might sound strange, given people are requesting things like this, but really we have so many other projects going on at @dosyago particularly with @BrowserBox it's just full on. 

Happy to provide guidance if you want take a shot at this yourself. Thanks for your ideas/thoughts/questions and feedback, @brimwats !

**Comment by crisdosaygo** [comment]
@brimwats we now support others! :)
