### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by TangentFoxy** [c9fe/22120#193]
The readme gives instructions on installing this, which uses the global flag for some reason, but then what? I have apparently installed it but I don't see anything about how to actually start using it.

**Comment by crisdosaygo** [comment]
Hey @TangentFoxy thank you for your question. Just to help us get started assisting you, do you mind sharing how you installed it? Should be able to help you out from there, once we know a bit more! Also what is your system? Are you seeing anything right now? Thank you!

**Comment by TangentFoxy** [comment]
- `npm i -g diskernet@3.0.6`
- Windows 10
- How and where should I be seeing anything? As far as I can tell, I've installed some stuff but there was nothing about how to run it.

**Comment by o0101** [comment]
Should work!

**Comment by crisdosaygo** [comment]
@TangentFoxy should work!
