### ISSUE TITLE
binary release does not work on linux

### ISSUE THREAD

**Issue by herberthamaral** [c9fe/22120#55]
I tried to download the latest `.nix` binary release but when I tried to execute it on my manjaro linux box I got the following error: 

```
internal/bootstrap/pre_execution.js:81
    throw 'Invalid Nexe binary';
    ^
Invalid Nexe binary
```

Am I missing something?

Thanks!

EDIT: add env info.

**Comment by c9fe** [comment]
Hey @herberthamaral i feel sorry for you about that. That must seem disappointing. I'll take a look at it.

In the meantime, please try using the npm install route, or downloading from an earlier release.

**Comment by c9fe** [comment]
I can confirm this issue on Ubuntu with the latest release. I'm working on a fix.

**Comment by c9fe** [comment]
@herberthamaral I just pushed a new release and confirmed the binary works on linux. It should work for you, I hope it does!
