### ISSUE TITLE
Runs, does not save pages, errors in the shell [maintainer: Please rename this bug]

### ISSUE THREAD

**Issue by WaterSibilantFalling** [c9fe/22120#56]
First, my browser is ungoogled-chromium, which might be too far from chrome?

Second, I don't think that this is the same as #55, but it might be(?)

Thirdly:

### Browser:

*  Version 84.0.4147.135 (Developer Build) built on Debian buster/10, running on Debian buster/10 (64-bit)

but ungoogled-chromium fakes everything to be identical to 'googled' chromium, so make of that what you will

### node.js

* 15.2.0

> nvm list
->      v15.2.0
         system
default -> node (-> v15.2.0)
node -> stable (-> v15.2.0) (default)
stable -> 15.2 (-> v15.2.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/fermium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.23.0 (-> N/A)
lts/erbium -> v12.19.0 (-> N/A)
lts/fermium -> v14.15.0 (-> N/A)

### Machine

* Linux Isis 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux

### Error

```

> npm start

> archivist1@1.3.9 start /bench/github_local/DOWN_ONLY/22120
> node index.js

Args usage: <server_port> <save|serve> <chrome_port> <library_path>
Running in node...
Importing dependencies...
Attempting to shut running chrome...
There was no running chrome.
Removing 22120's existing temporary browser cache if it exists...
Launching library server...
Library server started.
Waiting 1 second...
{"server_up":{"upAt":"2020-11-11T23:31:03.469Z","port":22120}}
Launching chrome...
(node:6104) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:6104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6104) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFileSync' of undefined
    at saveCache (/bench/github_local/DOWN_ONLY/22120/archivist.js:436:8)
    at Object.changeMode (/bench/github_local/DOWN_ONLY/22120/archivist.js:416:3)
    at app.post (/bench/github_local/DOWN_ONLY/22120/libraryServer.js:59:21)
    at Layer.handle [as handle_request] (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/layer.js:95:5)
    at next (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/layer.js:95:5)
    at /bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/index.js:335:12)
    at next (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/index.js:275:10)
(node:6104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6104) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeFileSync' of undefined
    at saveCache (/bench/github_local/DOWN_ONLY/22120/archivist.js:436:8)
    at Object.changeMode (/bench/github_local/DOWN_ONLY/22120/archivist.js:416:3)
    at app.post (/bench/github_local/DOWN_ONLY/22120/libraryServer.js:59:21)
    at Layer.handle [as handle_request] (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/layer.js:95:5)
    at next (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/layer.js:95:5)
    at /bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/index.js:335:12)
    at next (/bench/github_local/DOWN_ONLY/22120/node_modules/express/lib/router/index.js:275:10)
(node:6104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

**Comment by c9fe** [comment]
Thanks @WaterSibilantFalling for all the information. Again, i feel sorry for you this happened, and it must seem frustrating for you. 

This error means that we couldn't connect to the chrome browser over the debugging port. You might be right that your browser build could have something to do with it. 

I'll take a look. In the meantime, you might try installing Google chrome stable if you want to test it. I think it's unrelated to the other issues you mention. At the same time i understand if you will only use this browser build you mention. If so, i don't have a workaround for you for the meantime.

Do you have a source for your ungoogled-chrome so that i can get a copy to test?

**Comment by c9fe** [comment]
Another workaround I thought about in the meantime is you can try altering the chrome port, which defaults to 9222. It might be the case that you have something running on that.  To get some more useful debugging output, you could run it with the environment variable `DEBUG_22120` set to something (any non empty string).

So try starting up like:

```console
$ node index.js 22120 save 53916`
```

where 13916 is the random chrome port you want to try.

Also to get the latest debugging info (including chrome status), please pull the latest copy of the repo. Thanks!

**Comment by c9fe** [comment]
Another workaround I thought about in the meantime is you can try altering the chrome port, which defaults to 9222. It might be the case that you have something running on that.  To get some more useful debugging output, you could run it with the environment variable `DEBUG_22120` set to something (any non empty string).

So try starting up like:

```console
$ node index.js 22120 save 53916
```

where 13916 is the random chrome port you want to try.

Also to get the latest debugging info (including chrome status), please pull the latest copy of the repo. Thanks!

**Comment by c9fe** [comment]
Thanks @WaterSibilantFalling for all the information. Again, i feel sorry for you this happened, and it must seem frustrating for you. 

This error means that we couldn't connect to the chrome browser over the debugging port. You might be right that your browser build could have something to do with it. Alternately, it could be your browser is running and we couldn't shut it down, or other things. 

If you set the env variable like i said above and get the latest code, you'll see some more debugging info. If you say that, I might be able to help you diagnose.  

In the meantime, you might try installing Google chrome stable if you want to test it. I think it's unrelated to the other issues you mention. At the same time i understand if you will only use this browser build you mention. I don't have any other workarounds for you.

**Comment by c9fe** [comment]
Thanks @WaterSibilantFalling for all the information. Again, i feel sorry for you this happened, and it must seem frustrating for you. 

This error means that we couldn't connect to the chrome browser over the debugging port. You might be right that your browser build could have something to do with it. Alternately, it could be your browser is running and we couldn't shut it down, or other things. 

In the meantime, you might try installing Google chrome stable if you want to test it. I think it's unrelated to the other issues you mention. At the same time i understand if you will only use this browser build you mention.

If you set the env variable like i said above and get the latest code, you'll see some more debugging info. If you say that, I might be able to help you diagnose if i get back to this issue in future.
