### ISSUE TITLE
Documentation: how to execute binary?

### ISSUE THREAD

**Issue by pjwalstrom** [c9fe/22120#59]
How is the binary supposed to be executed? Can not see any documentation on it
```
➜  file 22120.macos
22120.macos: Mach-O 64-bit executable x86_64
➜  open 22120.macos
No application knows how to open 22120.macos.
```

**Comment by c9fe** [comment]
Thank you for that. I'm investigating.

**Comment by c9fe** [comment]
I feel very sorry for you that you're having this problem. Do you know your system architecture?

You could try running:

```console
$ uname -a
```


```console
$ /usr/bin/arch
```

What might have happened is your Mac may not have the `x86_64` architecture. 

If you don't post back I won't be able to help you more now as I don't have a Mac in front of me now.

**Comment by pjwalstrom** [comment]
```
➜  uname -a
Darwin foo.lan 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
➜  /usr/bin/arch
i386
```

**Comment by c9fe** [comment]
Thanks @pjwalstrom 

The architecture seems to be right for the binary. 

I'm not sure. Let me investigate further.

**Comment by c9fe** [comment]
Try downloading the binary from the latest release.

And try this. 

https://support.apple.com/en-ie/guide/mac-help/mh40616/mac

If it doesn't work and you let me know what happens I can investigate further.

**Comment by c9fe** [comment]
@pjwalstrom Try downloading the binary from the latest release.

And try this. 

https://support.apple.com/en-ie/guide/mac-help/mh40616/mac

If it doesn't work and you let me know what happens I can investigate further.

**Comment by pjwalstrom** [comment]
same error message ("No application knows how to open 22120.macos"). If it was an unidentified developer, the error message would have been "can't be opened because it is from an unidentified developer".

**Comment by c9fe** [comment]
I feel so bad for you that you're still having trouble with this. It must be so frustrating  and disappointing for you. If you have node and npm installed a workaround in the meantime might be to simply:

```console
$ npm i -g archivist1@latest
$ archivist1
```

For the binary, try:

```console
$ chmod +x ./22120.macos
$ ./22120.macos
```

```console
$ mv ./22120.macos ./22120
$ ./22120
```

Rebooting.

`open 22120` after you have done these steps. 

Also you could try the following, **Update prebinding** from here. https://www.cnet.com/news/tutorial-what-to-do-when-a-mac-os-x-application-will-not-launch/

I feel so sorry for you that I cannot provide you more help until I have a Mac in front of me. It might be some time. If these options don't work, and you let me know it's not working, I could probably investigate more for you in future.

**Comment by c9fe** [comment]
@pjwalstrom I feel so bad for you that you're still having trouble with this. It must be so frustrating  and disappointing for you. If you have node and npm installed a workaround in the meantime might be to simply:

```console
$ npm i -g archivist1@latest
$ archivist1
```

For the binary, try:

```console
$ chmod +x ./22120.macos
$ ./22120.macos
```

```console
$ mv ./22120.macos ./22120
$ ./22120
```

Rebooting.

`open 22120` after you have done these steps. 

Also you could try the following, **Update prebinding** from here. https://www.cnet.com/news/tutorial-what-to-do-when-a-mac-os-x-application-will-not-launch/

I feel so sorry for you that I cannot provide you more help until I have a Mac in front of me. It might be some time. If these options don't work, and you let me know it's not working, I could probably investigate more for you in future.

**Comment by c9fe** [comment]
@pjwalstrom I feel really terrible for you this is still an issue for you. I might put this issue aside, or I might come back to it in future. For now, I had one more idea.

We use `upx` to shrink the binaries. There have been reported issues with some `upx` shrunk binaries on Mac. So to help you I just uploaded a new release as a test without the upx shrinking.

You could download and try it:

https://github.com/c9fe/22120/releases/download/v1.3.13/22120.noupx.macos

If it doesn't work and you let me know, that might help when I have a Mac in front of me, if and when I get back to this in future. I feel sorry for you that this is an issue for you, and I also need to put a block on more work on this issue for now.

**Comment by c9fe** [comment]
@pjwalstrom I feel really terrible for you this is still an issue for you. I might put this issue aside, or I might come back to it in future. For now, I had one more idea.

We use `upx` to shrink the binaries. There have been reported issues with some `upx` shrunk binaries on Mac. So to help you I just uploaded a new release as a test without the upx shrinking.

You could download and try it:

https://github.com/c9fe/22120/releases/download/v1.3.13/22120.noupx.macos

If it doesn't work and you let me know, that might help when I have a Mac in front of me, if and when I get back to this in future. It must be very annoying for you to have this issue. I feel sorry for you that this is an issue for you, and I also need to stop any more work on this issue for now.

**Comment by pjwalstrom** [comment]
tried the noupx version without luck, have not tried npm. Running the binary just kills the process instantly. No logs to be found in syslog or other places I've looked. Binary has correct execution rights
```
➜  ./22120.macos 
[1]    72865 killed     ./22120.macos 
```
