### ISSUE TITLE
SPA JavaScript 

### ISSUE THREAD

**Issue by m1sta** [c9fe/22120#60]
Are there plans to support apps like outlook.com, Reddit, and Twitter with complex JavaScript that looks at the current url?

**Comment by c9fe** [comment]
They already work. But note that nothing will be saved unless you actually click on that part of the page to trigger that action.

For example, I can archive my GMail web app, but it works like this.

If I load it in `serve` mode, I see the list of emails, but unless I clicked through on an email to expand it to full view when I was in `save` mode, I won't be able to load that email into detail view in serve mode.

I feel pretty scared you won't have a good experience of this, unless you understand that. 

There's no "automatic" saving. The only things that are saved are whatever the browser loads in response to your browsing, navigation, acting on the page, etc.
