### ISSUE TITLE
Some pages are broken

### ISSUE THREAD

**Issue by yamrzou** [c9fe/22120#62]
I want to save a list of web pages. Let's call them A,B,C,D,... etc.
Once a given page loads, I can press a "play" button which loads some interactive javascript content for some time (a few minutes), then the page automatically redirects to the next one (the browser URL automatically changes too). Then I press the play button again and so on. Similar to playing videos from a YouTube playlist, but there is no video.
A redicrects to B, which redirects to C, etc.

I noticed that the first page A is archived correctly, i.e. I can click on the play button from the saved page and it would work like the live one, but the next pages B,C,... etc are broken. Any idea what could cause this?

Thank you.

**Comment by c9fe** [comment]
I think it's related to the resources not being saved against the automatically updated URL, rather against the original URL. As far as i remember, i don't index on history push state URL changes, only on navigation. So these pages may not be in the index. 

If you provide a sample URL it might help diagnose if i come back to this issues in future. Also, information about whether the original flow still works if you start with A, but only breaks of your try to load the URL of B, might help too.
