### ISSUE TITLE
Enhancement Idea: Multiple caches

### ISSUE THREAD

**Issue by nobicycle** [c9fe/22120#65]
Suggestion: Allow multiple caches, so the user could launch archivist1 -c \<cache-name\>

So users could create archives for certain sites.

Example:
archivist1 -c 22120

Would be the cache the user used for browsing https://github.com/c9fe/22120

**Comment by c9fe** [comment]
I feel really touched you made this suggestion! I really appreciate it. Thank you

Good idea, but you can already do that by setting the archive root in the settings pane. I do like the command line argument tho. I'll come back to this and decide later.
