### ISSUE TITLE
Change chrome path location

### ISSUE THREAD

**Issue by graphixillusion** [c9fe/22120#68]
Hi there. I was trying this software and it works ok with chrome installed. On another machine i don't have chrome installed becouse i'm using portable version of ungoogled-chromium. Is it possible to change the chrome's exe location so this program can start it without any issue? Thank you.

**Comment by c9fe** [comment]
You could try copying the chrome binary you have to the location where chrome launcher expects it to be, or linking it. Alternately, you could set the [`CHROME_PATH`](https://github.com/GoogleChrome/chrome-launcher#launchopts) environment variable to the  location of your binary.
