### ISSUE TITLE
Introduce an "expert mode" that does not kill or attempt to start Chrome

### ISSUE THREAD

**Issue by banhigh** [c9fe/22120#74]
Thank you, a lot for working hard and then open sourcing this.

Using Chrome remote debugging is brilliant, it makes archiving exact. There is a LOT of potential in this project and I hope to help you.

I am going to be putting in hundreds of hours of effort into this great project but before I proceed I wanted to ask you:

Are you OK with an "**expert mode**"?

In this mode, meant for advanced users and developers/contributors to this project:

1. 22120 runs inside a docker container based off the node docker image
2. It does not try to terminate/start Chrome instances directly (as it currently does). Instead, it connects over the remote-debugging-port at localhost:9222
3. If it cannot connect, it terminates with error message
4. If it can connect, it starts the webserver and prints a message to the (docker) console saying "Connected successfully to remote-debugging-port at localhost:9222. Visit localhost:22120 to control 22120 itself"

I understand the reason why you terminate all Chrome instances in the chrome launcher, because when `--headless` is not used (as in the case of 22120 users) and there is already an instance of Chrome running, Chrome then opens the new window in the existing browser instance and hence fail to enable the debugging port which 22120 depends on if the original instance of Chrome did not have debugging port enabled.

Expert users might not want to kill all of their Chrome instances but have 22120 try and connect to 9222 if available. This is why I am proposing an "expert mode".

Now, I don't want to burden you and I am not asking you to implement this "expert mode" - I can send you a PR that does this.

I am only asking you if you like this idea and will merge the PR if I add this "expert mode" :)
Are you OK with it? :D

Thank you again, this is a great project :tada:

**Comment by c9fe** [comment]
I do appreciate the effort you've put into this proposal and I'm grateful that you find this software useful and want to be part of it.

I don't think there's a place for this feature in the current version right now.
