### ISSUE TITLE
Any way to clean/delete entries?

### ISSUE THREAD

**Issue by johnhorsema** [c9fe/22120#91]
Somtimes I have mis-clicked some links e.g. ads and would like to remove them from the archive. Is there a way to do so?

**Comment by crisdosaygo** [comment]
No. But I will add this.

Currently the only way to do that is either with a "no file" (see the README, it's like a domain blocklist). Or using your regular ad blocker (they won't be saved if blocked by your ad blocker).

But I'll add the ability to easily delete entries, as well as to selectively add them.

**Comment by i5ik** [comment]
Also add a way to 'block' a URL or even domain from ever being saved again.
