### ISSUE TITLE
rebrand

### ISSUE THREAD

**Issue by crisdosaygo** [c9fe/22120#93]

**Comment by crisdosaygo** [comment]
diskernet

- create you an internet 
- the internet on your disk
- by the power of the diskernet
- are you sure you want to delete this facebook.com from the internet?
- publish an internet

**Comment by crisdosaygo** [comment]
also has to have the 3.5" floppy icon as logo. has to

**Comment by crisdosaygo** [comment]
also add retro stylings

**Comment by crisdosaygo** [comment]
@foone can I use your Twitter image as a logo for this project? I like it and might be interested to use it.

**Comment by foone** [comment]
That's fine with me, but I didn't create it. It's from Windows 95.

**Comment by crisdosaygo** [comment]
Thank you, I'll look into this whole thing more deeply. Windows 95 is a classic--classic icons.

**Comment by crisdosaygo** [comment]
I think a cool idea would be the old netscape animated icon, but instead of an N, it's a floppy disk sitting on a hill surrounded by shooting stars.

**Comment by crisdosaygo** [comment]
Looking at the Netscape animated GIF, I think I could probably do this, if there was some way to frame by frame pixel edit a gif

**Comment by crisdosaygo** [comment]
Then I could probably combine that with Win95 or other cool retro pixelated floppy disk icon, and that would be 'fair use' or a derivative work and so avoid any weird branding or copyright issues

probably

**Comment by crisdosaygo** [comment]
![diskernet-logo-first-draft](https://user-images.githubusercontent.com/22254235/147733825-1a031509-a03a-4d01-9106-5ce81eb79f6d.gif)

first draft
